name: Deploy Server to Azure App Service

on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "server/package-lock.json"

      - name: Install deps
        working-directory: server
        run: npm ci

      - name: Build (if TypeScript)
        working-directory: server
        run: npm run build --if-present

      # Zip ONLY the server folder (exclude node_modules so Azure does a clean prod install)
      - name: Create deployment package
        run: |
          zip -r server.zip server -x "server/node_modules/**" "server/.git/**" "server/.cache/**"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Ensure Azure does a remote build with Oryx (installs prod deps, respects package.json "start")
      - name: Enable remote build + Node default version
        run: |
          az webapp config appsettings set \
            --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
            --name "${{ secrets.AZURE_WEBAPP_NAME }}" \
            --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true WEBSITE_NODE_DEFAULT_VERSION=~20

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: server.zip
