name: Deploy Server to Azure App Service

on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install deps locally to catch missing/broken lockfiles early (optional)
      - name: Install deps (local)
        working-directory: server
        run: npm ci || npm install

      - name: Build (if TypeScript)
        working-directory: server
        run: npm run build --if-present

      # IMPORTANT: zip the *contents* of server/ so package.json is at the zip root
      - name: Create deployment package
        working-directory: server
        run: |
          zip -r ../app.zip . -x "node_modules/**" ".git/**" ".cache/**"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Enable remote build + Node default
        run: |
          az webapp config appsettings set \
            --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
            --name "${{ secrets.AZURE_WEBAPP_NAME }}" \
            --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true WEBSITE_NODE_DEFAULT_VERSION=~20

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: app.zip
